### ISSUE TITLE
Redis queue class based on rpush/lpop

### ISSUE THREAD

**Issue by shicky** [aio-libs/aioredis#123]
For my application, I have redis queue class that wraps around rpush/lpop.
Is it possible to include in util.py?

**Comment by ushuz** [comment]
`aioredis` is a general purpose Redis driver / connector, while queue is a specific purpose application. Queue is not what a driver needs to do its job, so I think it shouldn't be included in `aioredis`.

**Comment by shicky** [comment]
Perhaps you are right.
But I still think it is common use-case for Redis and wouldn't hurt to be included.

**Comment by popravich** [comment]
Hi guys,
I agree with ushuz that such `Queue` should not be included in `aioredis`,
because its hard to satisfy everybodys needs: someone may want Queue based on lists
someone may want it based on sorted sets, someone may want it to be built with some other concept.

Anyway, you can publish you Queue implementation on pypi and give me a link to be included in docs.
I think it would be really helpful for lib users to see a list with such extensions.

**Comment by popravich** [comment]
As for PR, it has some inconsistencies and may not work as expected, if you want I can comment what is wrong.

**Comment by shicky** [comment]
Thank you Alexey.
Could you please provide some feedback on current implementation?

Best Regards,

Steve (Sick) Yoon
(647) 760 - 2280
