### ISSUE TITLE
Change the hiredis install method.

### ISSUE THREAD

**Issue by AraHaan** [aio-libs/aioredis#197]
A newer version of hiredis is available on github not pip. It would have to be installed lik this instead:

```cmd
pip install --upgrade https://github.com/redis/hiredis-py/archive/master.zip
```

Hope you understand that the one on PyPi was so old that it is legit 2 years ago. So the github one is more or so along the lines of current.

**Comment by WoLpH** [comment]
It would be wonderful if the hiredis requirement would be optional, it's requiring me to do a `pip uninstall -y hiredis` after every install right now due to hiredis bugs (specifically: https://github.com/celery/celery/issues/3898)

Using extras would easily solve the issue: https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

**Comment by seocam** [comment]
This has been discussed here: https://github.com/aio-libs/aioredis/pull/317
We are currently using hiredis in a "forced" way because `channels_redis` depends on `aioredis` which installs it. The problem with that is that our celery just freeze in a really short period of time. 

I know that the ideal solution would be to fix Celery but this still could happen again with other libs. 

IMHO `aioredis` should explicitly assume it depends on `hiredis` or the install method should be changed to allow it to be actually optional.

**Comment by popravich** [comment]
This all is so unrelated to aioredis!

**Comment by popravich** [comment]
ok, you all just made me waste half of my day to dig in into totally unrelated issue(
check out this PR (celery/kombu#954) and report if it works for you (preferably in proper repo/issue).

**Comment by WoLpH** [comment]
I've monkeypatched celery/kombu similarly before and it didn't work for me.

As for being unrelated to aioredis, there is no need for hiredis within aioredis as it works perfectly fine on the regular redis client so it should be optional.

**Comment by WoLpH** [comment]
There are several reasons not to want (or need) `hiredis`:

1. As demonstrated in the kombu issue, hiredis has non-trivial bugs
2. Installing hiredis is not always easily done, unless there's a binary wheel available for your platform you'll have to compile it yourself. Compiling it yourself requires either root access so you can install the compiler and the headers, or a lot of manual fiddling.
3. In most real-world scenarios the overhead from using pure python instead of hiredis is negligible. The time it takes to parse the 4096 bytes string in hiredis is 1.5ms whereas the pure python version is 4.1ms. That's indeed 2.73 times faster but still a tiny amount.

As for sharing my findings. There are several issues on Github relating this bug and I have shared my findings several of them. I have spent a significant amount of time trying to solve the bug but I've been unable to track it down fully so I've simply given for the time being.

I'm all for performance but when it compromises stability it's simply not worth it. Instability results in me having to wake up in the middle of the night to fix issues, a tiny performance difference is something I can account for.

**Comment by popravich** [comment]
> 1. As demonstrated in the kombu issue, hiredis has non-trivial bugs

Again, its not the bug in hiredis! its a bug in kombu and redis-py.
> 2. Installing hiredis is not always easily done

Agree, but there are hiredis wheels for common platforms (https://pypi.org/project/hiredis/#files)

> 3. In most real-world scenarios the overhead from using pure python instead of hiredis is negligible.

I have a python web application which calls Redis on each request and Redis average response time
is around 0.9 ms. Increasing it with pure-python parse would mean decreasing app's RPS and thus requiring more hardware to serve the same traffic.

**Comment by WoLpH** [comment]
> Again, its not the bug in hiredis! its a bug in kombu and redis-py.

I would argue it's a bug in both actually. It's definitely kombu/redis-py triggering the issue, but they're triggering a bug in hiredis. Pure Python shouldn't be able to freeze your Python completely in an unrecoverable state :)

> Agree, but there are hiredis wheels for common platforms (https://pypi.org/project/hiredis/#files)

Indeed, but not all. So let me ask you, why should an optional requirement be made required by this library?

> I have a python web application which calls Redis on each request and Redis average response time
> is around 0.9 ms. Increasing it with pure-python parse would mean decreasing app's RPS and thus requiring more hardware to serve the same traffic.

I don't see your point to be honest? We know it's faster and depending on the use case that can be relevant. But I still value sleep over adding a bit of hardware ;)

In my case the hiredis overhead is so tiny that the performance difference was barely noticable so it doesn't matter much either way.

**Comment by popravich** [comment]
Lets stop this discussion. Your main problem is with celery, so lets fix that! We can discuss it on gitter or in celery issue.

**Comment by WoLpH** [comment]
No, the main issue is not with celery. The issue is with hiredis since the exact same celery code works reliably without hiredis. So even if there's a bug in celery/kombu, it's triggering the actual bug in hiredis.

I would still like my question to be answered though: why should an optional requirement be made required by this library?

For the time being I'll simply leave the `pip uninstall hiredis` in my deploy flow :)
Celery is not the only bit of code that uses redis within my project so that could be the reason the fix doesn't work for me.

**Comment by seocam** [comment]
Hi @popravich! I'm really sorry you feel like you waste half of you day and at the same time I'm really grateful you spent this time trying to help us! Thank you for that.

About this issue here: you just closed an issue that asks for `hiredis` to be an optional dependency. In this sense optional would mean to let the user decide if he wants the performance you are perceiving or less dependencies in his application. Not everybody has performance as the primary reason for their choices.

Thanks again @popravich!

**Comment by asvetlov** [comment]
I support @popravich in his decision.
`hiredis` has no bug. The problem was in kombu which did not work properly with opened sockets. 
`hiredis-py` itself, in turn, has no any deal with sockets or file descriptors: it is a parser of incoming byte stream into data messages.

Regarding optional dependency for optimized (and not buggy) code.
Let's assume we have a library X. Another library Y uses it. I develop a library Z which optionally use X but by my fault has an integration problem. 
The question is: should I fix Z or enforce Y's author to get rid of X or make it an optional dependency?

To be more concrete: `aiohttp` uses C extensions by default. It also depends on `yarl` and `multidict` with optional but enabled by default C extensions as well.
Should I disable all optimizations in `aiohttp` / `multidict` / `yarl` and convert them to opt-in?
If you don't like/use aiohttp -- let's consider suggesting Mike Bayer disable C optimizations in `sqlalchemy`.
Finally, following this way we should disable all C optimizations for CPython itself by default. The list of them is huge: about one third of https://github.com/python/cpython/tree/master/Modules is optional.

I think the speed is quite important. If the optimization has a bug -- the bug should be fixed. If it has no bugs -- there is no reason to make it opt-in.

**Comment by seocam** [comment]
It's a little unclear what you mean and why this is here:
```
Note

hiredis is preferred requirement. Pure-python protocol parser is implemented as well and can be used through parser parameter.
```
From: https://github.com/aio-libs/aioredis/blob/master/README.rst#requirements

I do understand all the reasons you have stated and it makes total sense to support hiredis! I just can't understand why you don't want to give the power of choice to the programmer using the library.

Anyway that's the last comment I'm sending here and I'm feeling we don't want to be heard.
Sorry for bothering you.

**Comment by WoLpH** [comment]
> hiredis has no bug. The problem was in kombu which did not work properly with opened sockets.
hiredis-py itself, in turn, has no any deal with sockets or file descriptors: it is a parser of incoming byte stream into data messages.

The exact same code works perfectly fine without hiredis and freezes your whole python instance with hiredis. How else would you classify that, if not a bug?

**Comment by asvetlov** [comment]
> The exact same code works perfectly fine without hiredis and freezes your whole python instance with hiredis. How else would you classify that, if not a bug?

I recall a story. 
aiohttp static file server worked fine with `asyncio` but crashed when executed under `uvloop`. Was it `uvloop` bug? No, `aiohttp` did weird things to provide `sendfile` facility while `asyncio` itself did not support it yet itself.
The bug was fixed in aiohttp about 3 years ago. I did not blame that `uvloop` is hard to debug (it is, really) and buggy (it isn't) but figured out what is going on and applied required changes.

**Comment by WoLpH** [comment]
Please look at the following two results:

- https://github.com/celery/kombu/search?q=hiredis&unscoped_q=hiredis
- https://github.com/aio-libs/aiohttp/search?utf8=%E2%9C%93&q=uvloop&type=

As I said earlier in this discussion, it's either a bug in hiredis or in the hiredis wrapper which I indeed both call "hiredis" for the ease of discussion. Since kombu is not doing anything different for hiredis (it's not even aware of the difference) it cannot be fully held responsible for this bug.

> BTW, all aiohttp / yarl/ multidict doesn't need Cython to install.
When installing a binary wheel they use precompiled C Extensions.
On installing from a tarball only C compiler is required because the tarball is shipped with translated .pyx -> .c files.

And that is exactly my point. All of those libraries gracefully fall back to pure Python if they are unable to install the speedups module.
