### ISSUE TITLE
CancelledError cannot be handled properly ,when i use websocket.

### ISSUE THREAD

**Issue by larry-dev** [aio-libs/aioredis#315]
Hi @popravich 
our application the user access using realtime mode. 
We have a scenario that requires the user to close the application and continue processing the data.
but the user close application threw cancelled from aioredis.

Can you tell me how to ignore this mistake by the aioredis?
Thanks very much!!!

**Comment by asvetlov** [comment]
Wrong bugtracker.

**Comment by popravich** [comment]
@larry-dev , I've just made a v0.3.5 release with a fix for obscure CancelledError, see #316.
Before fix aioredis was cancelling pending commands in case of connection errors,
with this release it has been fixed to explicitly set distinct exception for pending commands.
Try upgrading and you should be able to see if this issue is related to redis/aioredis
(if connection to redis is being lost you should see either `ConnectionError` or `aioredis.ConnectionClosedError`)
