### ISSUE TITLE
PubSub hangs on disconnect

### ISSUE THREAD

**Issue by dfee** [aio-libs/aioredis#354]
It seems I can manually close a subscription in Redis `CLIENT KILL ID xyz`, and mpsc.get() will continue to hang. https://github.com/aio-libs/aioredis/blob/master/aioredis/pubsub.py#L259

This seems like a bug. Is there some way I should be manually checking (on a timeout) if we're still in pubsub mode?

I.e.
```python
while True:
    result = await asyncio.gather(asyncio.sleep(1), mpsc.wait_message())
    if result[0]:
        if not pool.connection.in_pubsub:
            break
    if result[1]:
        yield await mpsc.get()
```

**Comment by popravich** [comment]
The fix is in master, please try it.

**Comment by gjcarneiro** [comment]
I'm testing aioredis master, this seem to work very well, good job!

**Comment by gjcarneiro** [comment]
When can we expect a release? I'm currently running in production with revision e706ea3d18afda3166a1b867622c68da82943a79 from git, because of this bug.

On one hand, great, I had another incident last night with my service losing connection to the redis server (some kind of network glitch), and it recovered correctly from that.  But I would rather be using a proper release, than git...

**Comment by popravich** [comment]
aioredis v1.1 already released

**Comment by gjcarneiro** [comment]
Yes, thanks!  Silly of me for not checking... :man_facepalming:
