### ISSUE TITLE
Why does connection pool context much slower then pool.execute()?

### ISSUE THREAD

**Issue by asleea88** [aio-libs/aioredis#390]
I have measured the time for two way to use a connection pool. The one is with `context` statement and the other is just with calling `execute()`.

I expected the `context` statement is surely faster because it could re-use a connection acquired in contrast to the latter. 

For example
```
async def test(pool):
    with await pool as con:   # Reuse con for the three commands.
        a = await con.execute('GET', 'a')
        a = await con.execute('GET', 'a')
        a = await con.execute('GET', 'a')
```
```
async def test2(pool):
    await pool.execute('GET', 'a')   # Should acquire connection  every time.
    await pool.execute('GET', 'a')   # Should acquire connection  every time.
    await pool.execute('GET', 'a')   # Should acquire connection  every time.
```
But somehow, the result is the reverse and even calling `execute()` is faster almost two times.

Why?

The below is the test code I did.

aioredis1.0.0
python3.6.3
Redis server v=3.0.6
```
from timeit import timeit


setup = """
import aioredis
import asyncio
import uvloop
LOOP_POLICY = uvloop.EventLoopPolicy()  
asyncio.set_event_loop_policy(LOOP_POLICY)
loop = asyncio.get_event_loop()

pool = loop.run_until_complete(aioredis.create_pool(
    '/home/user/workspace/run/redis.sock', maxsize=100, minsize=100
    ))
"""

stmt1 = """
async def test(pool):
    with await pool as con:
        a = await con.execute('GET', 'a')
        a = await con.execute('GET', 'a')
        a = await con.execute('GET', 'a')

l = []
for i in range(10000):
    l.append(test(pool))

loop.run_until_complete(asyncio.gather(*l))
"""
stmt2 = """
async def test2(pool):
    await pool.execute('GET', 'a')
    await pool.execute('GET', 'a')
    await pool.execute('GET', 'a')

l = []
for i in range(10000):
    l.append(test2(pool))

loop.run_until_complete(asyncio.gather(*l))
"""

print('pool context : ', timeit(stmt1, setup=setup, number=1))
print('pool execute : ', timeit(stmt2, setup=setup, number=1))
```

**Comment by popravich** [comment]
Hi, @asleea88 
Let me explain,

> I expected the `context` statement is surely faster because it could re-use a connection acquired in contrast to the latter.

> But somehow, the result is the reverse and even calling execute() is faster almost two times.

Since version v1.0 pool implements `AbcConnection` interface. This, basically, means that pool has `execute` method, so the need to use context manage to explicitly acquire connection become unnecessary.
The implementation of this sounds straight-forward — just `acquire`/`release` connection in `execute` method, but its not.

I wanted to keep the nice pipelining feature **[1]**, so `pool.execute` had to implement it too.

So, the `ConnectionsPool` has two modes **[2]**, **[3]**:
* Exclusive mode — when you acquire/release connection with either context manager or explicitly
```python
with await pool as conn:
    await conn.execute(...)
```

* Shared mode — when `execute` method **does not lock** the connection for command but
picks a free one and sends command through it. If there are no free connections it execute switches to exclusive mode and will block and acquire connection for use.
```python
await pool.execute(...)
# if there is a free connection in pool it will be used without locking.
```

Now, why using context manager is slower than calling execute directly.

In your test you create a pool with 100 connections, then you start 10000 concurrent tasks.
For `stmt1` first 100 tasks will acquire all free connections from pool and the rest 9900 tasks
will block waiting for one to get released.
In contrast, all tasks from `stmt2` will share all 100 connections to send commands
(without locking connections).

There is one **important note** to remember when to use context manager explicitly:
when you execute some blocking commands like `blpop` or long-running Lua scripts
you must acquire exclusive connection otherwise it can block other tasks using redis.
```python
pool = ...

async def bad_task():
    return await pool.execute('blpop', 'list', timeout=30)
asyncio.ensure_future(bad_task())
await pool.execute('get', 'key')  # This might block because 'blpop' could be sent before 'get'

async def good_task():
    with await pool as conn:
        return await conn.execute('blpop', 'list', timeout=30)
asyncio.ensure_future(good_task())
await pool.execute('get', 'key') # This won't block; 'blpop' is sent through reserved connection
```

**[1]**: http://aioredis.readthedocs.io/en/v1.1.0/start.html#commands-pipelining
**[2]**: http://aioredis.readthedocs.io/en/v1.1.0/migration.html#blocking-operations-and-connection-sharing
**[3]**: https://github.com/aio-libs/aioredis/issues/343

**Comment by asleea88** [comment]
Thank you for your answer! 

You said the reason why **Exclusive mod**(context manager) is slower is because it locks a connection.
As to **Shared mode**,  You use the word **`free`**  and you said they can share connections.

However, I am a little confused. 

What is different between `locked connection` and `connection not free`?
For me, both are the same in terms of performance because they are not available to other commands whether it is `locked `or `not free`.

For example
```
with await pool as conn:  # Acquire a connection
    await conn.execute(...)  # Execute a command
# Release the connection

# The connection was not available(because it is locked) while a command is executing
```


```
await pool.execute(...)

# A connection was not available(because it is not free) while a command is executing
```
A connection in both cases is not available to others while a command is executing.

**Comment by popravich** [comment]
Ok, a bit of internals:
Pool has two lists -- `free` connections list and `in-use` connections list.
With context manager you move connection from `free` to `in-use`, locking is needed to do some
maintenance on `free` list (drop closed connections, create new if list is empty). 
When context manager is done, connection is returned back to `free` list.
Without context manager no locking is performed and connection is not moved from one list to the other, the command is just sent through first connection from `free` list.
So *free connection* can be read as *one that can be acquired by context manager* and
*non-free* -- *the one acquired and in use by context manager*

Imagine simpler case: pool with `min` and `max`  size equal to 1 and 3 simultaneous tasks:

With context manager the timeline would look like this
```
T1: |--A---C1--C2--R
T2: |---W***********A--C1--C2--R
T3: |----W**********************A--C1--C2--R
    |--'---'---'---'---'---'---'---'---'---' <- loop steps
```
First task will acquire (**A**) the connection, two other will be waiting (**W**) until connection gets free.
Task 1 executes  two commands (**C1**, **C2**) and then releases (**R**) the connection. The cycle repeats for task 2 and then task 3.

This how the timeline would look in shared mode:
```
T1: |--C1--C2------
T2: |---C1--C2-----
T3: |----C1--C2----
    |--'---'---'---- <- loop steps
```

**Comment by asvetlov** [comment]
@popravich moving your explanations to docs would be great! 
Just make an auxiliary rst page with copy-paste your awesome comments.

**Comment by popravich** [comment]
Yeah, I have plans to rewrite the docs, but have no time yet(

**Comment by asleea88** [comment]
@popravich, So then, could I think **Shared mode** is preferred to **Exclusive mode**  for all cases if it doesn't consider transaction which has to use the identical connection for multiple commands and it is not long-term command?

**Comment by popravich** [comment]
@asleea88, yes.
