### ISSUE TITLE
[question] why you are using close and wait_close instead of just one method?

### ISSUE THREAD

**Issue by vanyakosmos** [aio-libs/aioredis#707]
I don't understand the reasoning behind having two method. Can someone explain or at least point out where I can read about this design choice?
Why don't we have just one async method `close` which can be scheduled with `asycnio.create_task` or awaited in place if user whats to be sure that connections are closed?

**Comment by sbdchd** [comment]
This is probably due to `close` and `wait_close` being defined on `asyncio.StreamWritier` class

https://docs.python.org/3/library/asyncio-stream.html#asyncio.StreamWriter.close

`.close()` will close the connection eventually so you don't need to call `wait_close` unless you don't want to proceed until the connection is actually closed.

Also note that `wait_close` was a new addition to that class in Python 3.7

related: https://github.com/python/asyncio/issues/466
