### ISSUE TITLE
connection param: timeout  do not work 

### ISSUE THREAD

**Issue by opt-m** [aio-libs/aioredis#799]
1. so i have a connection with timeout:
```
redis = await aioredis.create_redis(('127.0.0.1',6379), password='xxx',  timeout=3)
```

2. and use this command to block redis:
```
debug sleep 30
```

3. i expect get an  timeout error when query redis liket this:
```
await redis.info()
```
 but this connection just wait 30S and return normal data. 

i think this  ‘timeout' param doesn't work correctly。

**Comment by opt-m** [comment]
aioredis version: 1.3.1

**Comment by ognacy** [comment]
I am seeing the same issue. running with uvloop, gunicorn. Timeout is ignored. Attempting to wrap the redis operation in a task and use asyncio.wait_for with a timeout seems to solve the problem but I have a suspicion that such timed out operations leave open sockets and are not acceptable in a production environment

**Comment by ramonz** [comment]
This timeout param is only used to establish connection, not to command execution

**Comment by seandstewart** [comment]
Hey @opt-m - as @ramonz mentioned, the timeout param refers to acquiring a valid connection, which the client is still able to do, regardless of whether command execution is blocked.

If you wish to enforce a _command_ timeout, you can use a library like `async-timeout` or make use of asyncio's `asyncio.wait_for()`.

@ognacy regarding your concern about leaving an open socket, that should not be the case, but if you observe such behavior, I'd appreciate a ticket with possible reproduction so that we can triage and prioritize a fix appropriately.

For now, I'm going to close out this ticket.
