### ISSUE TITLE
How set expiration time to message in channel

### ISSUE THREAD

**Issue by codefather-labs** [aio-libs/aioredis#810]
I got `channel` channel: `aioredis.pubsub.Channel`
I got `redis` instance `aioredis.commands.Redis`

I want to push message into channel with expiration time
```
await redis.publish(
    channel=channel.name,
    message=await request.transport_serialize
)
```
But, `publish` method got no one `expiration` parameter like `redis.set()`. How i can set expiration time for channel message before sending? Thx

**Comment by wKavey** [comment]
Based on the redis docs for publish (https://redis.io/commands/publish) it doesn't look like this is possible. 

I'm not even sure how you would want it to work? I believe published messages are immediately routed to all subscribers of that channel, and cannot be picked up by new subscribers after the fact.

**Comment by seandstewart** [comment]
@codefather-labs -

@wKavey is correct, you can't expire messages within a pubsub channel. This is because messages are immediately pushed to all subscribed clients and are not retained once read.

For a more persistent topic-style subscription, you can look at [Redis Streams](https://redis.io/topics/streams-intro), which behave more closely to Kafka topics and are persistent in nature.
